[project]
name = "deupack"
version = "1.0.0"
description = "Python package to calculate structure of the deuteron"
authors = [
  {name = "Adam Freese", email = "afreese@jlab.org"},
  {name = "Alan Sosa", email = "asosa090@fiu.edu"}
]
maintainers = [
  {name = "Adam Freese", email = "afreese@jlab.org"}
]
readme = "README.md"
license = {file = "LICENSE"}
dependencies = [
  "cmasher",
  "matplotlib",
  "numpy",
  "pandas",
  "scipy"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.urls]
Homepage = "https://github.com/adamfreese/deupack.git"
Repository = "https://github.com/adamfreese/deupack.git"
